<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SuiteOneCaseTwo"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="11.374">
  <properties />
            <testcase name="SuiteOneCaseTwoTest" time="2.130" classname="SuiteOne.SuiteOneCaseTwo">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
ActualResult Value -2 And ExpectedResult Value -3 Not Match expected [-3] but found [-2]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
ActualResult Value -2 And ExpectedResult Value -3 Not Match expected [-3] but found [-2]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
  SuiteOne.SuiteOneCaseTwo.SuiteOneCaseTwoTest(SuiteOneCaseTwo.java:99)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:606)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:771)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
  org.testng.SuiteRunner.run(SuiteRunner.java:259)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1172)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
  org.testng.TestNG.run(TestNG.java:1009)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="SuiteOneCaseTwoTest" time="9.244" classname="SuiteOne.SuiteOneCaseTwo" />
      
</testsuite>
